version: '3'

services:
  postgres:
    image: "postgres:12"
    container_name: postgres
    ports:
      - "5430:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=usr
      - POSTGRES_DB=testdb
    network_mode: bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M
  web:
    build: .
    container_name: 4-hw-graalvm
    ports:
      - "8080:8080"
    entrypoint: "/app/4-hw-graalvm"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_URL=jdbc:postgresql://host.docker.internal:5430/testdb
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M