spring:
  application:
    name: web
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5430/testdb}
    user: usr
    password: pwd
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5430/testdb}
    username: usr
    password: pwd
  jpa:
    database: postgresql
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate